analytics/urls.py
from django.conf.urls import url
from . import views

app_name = 'analytics'
urlpatterns = [
    url(r'^', views.Analytics.as_view(), name='home'),
]

houses/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^', include('index.urls')),
    url(r'^analytics/', include('analytics.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

index/urls.py
from django.conf.urls import url
from . import views

app_name = 'index'
urlpatterns = [

    url(r'home/$', views.Home.as_view(), name='home'),
    url(r'signup/$', views.Signup.as_view(), name='signup'),
    url(r'login/$', views.Login.as_view(), name='login'),

]

index/templates/index/default/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Just keep swimming -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
      <!-- Favicon -->
    <link rel="icon" href="">

    <title>{% block title %}{% endblock %}</title>

    <!-- jQuery -->
    <script src="{% static 'index/js/jquery-3.1.1.min.js' %}"></script>
    <script src="{% static 'index/js/bootstrap.js' %}"></script>
    <!-- Bootstrap core CSS -->
    <link href="{% static 'index/css/bootstrap.min.css' %}" rel="stylesheet">


    <link rel="stylesheet" href="{% block css %}{% endblock %}">
  </head>
<body>
<header></header>
<div class="container">

    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'index:home' %}">Housing</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><a href="{% url 'analytics:home' %}">Analytics</a></li>
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="#">Action</a></li>
                <li><a href="#">Another action</a></li>
                <li><a href="#">Something else here</a></li>
                <li role="separator" class="divider"></li>
                <li class="dropdown-header">Nav header</li>
                <li><a href="#">Separated link</a></li>
                <li><a href="#">One more separated link</a></li>
              </ul>
            </li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li><a href="{% url 'index:login' %}">Login</a></li>
            <li class="active"><a href="{% url 'index:signup' %}">Sign Up<span class="sr-only">(current)</span></a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>
    {% block content %}
    {% endblock %}
</div> <!-- /container -->
<footer></footer>
</body>
</html>